# Generated by Django 4.2 on 2023-04-19 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_bid_alter_listing_initial_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid',
            new_name='current_bid',
        ),
    ]
