# Generated by Django 4.2 on 2023-04-19 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_bid_bid_current_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='current_bid',
            new_name='bid',
        ),
    ]
