# Generated by Django 4.2 on 2023-04-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_bid_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='counter',
            field=models.IntegerField(default=1),
        ),
    ]
